### ISSUE TITLE
Improve generate-dist script 

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/gravitee-ui-components#275]
Currently we just copy the css and i18n files from the assets, it would be nice to add a minification process

https://github.com/gravitee-io/gravitee-ui-components/blob/master/tasks/generate-dist.js#L107-L109

**Comment by gaetanmaisse** [comment]
After looking a bit at what is best as lib output it looks like we should go the opposite and ship the sources as it instead of minifiying them. The minification will be done later when building the app using `@gravitee/ui-component`, in our case by the Angular CLI (webpack under the hood).

**Comment by jgiovaresco** [comment]
FYI, I tried to upgrade Cockpit to Angular 12 and it seems Webpack 5 can't create a bundle using the minified code of ui-component.

```
Error: main.1daa4633808a68d06e2f.js from Terser
Unexpected token: punc (;) [main.1daa4633808a68d06e2f.js:153298,3154]
    at js_error (/Users/jgiovaresco/DEV/gravitee/cockpit/gravitee-cockpit/gravitee-cockpit-ui/node_modules/terser/dist/bundle.min.js:550:11)
    at croak (/Users/jgiovaresco/DEV/gravitee/cockpit/gravitee-cockpit/gravitee-cockpit-ui/node_modules/terser/dist/bundle.min.js:1274:9)
    at token_error (/Users/jgiovaresco/DEV/gravitee/cockpit/gravitee-cockpit/gravitee-cockpit-ui/node_modules/terser/dist/bundle.min.js:1282:9)
    at unexpected (/Users/jgiovaresco/DEV/gravitee/cockpit/gravitee-cockpit/gravitee-cockpit-ui/node_modules/terser/dist/bundle.min.js:1288:9)
    at expr_atom (/Users/jgiovaresco/DEV/gravitee/cockpit/gravitee-cockpit/gravitee-cockpit-ui/node_modules/terser/dist/bundle.min.js:2493:25)
    at maybe_unary (/Users/jgiovaresco/DEV/gravitee/cockpit/gravitee-cockpit/gravitee-cockpit-ui/node_modules/terser/dist/bundle.min.js:3294:19)
    at expr_ops (/Users/jgiovaresco/DEV/gravitee/cockpit/gravitee-cockpit/gravitee-cockpit-ui/node_modules/terser/dist/bundle.min.js:3345:24)
    at maybe_conditional (/Users/jgiovaresco/DEV/gravitee/cockpit/gravitee-cockpit/gravitee-cockpit-ui/node_modules/terser/dist/bundle.min.js:3350:20)
    at maybe_assign (/Users/jgiovaresco/DEV/gravitee/cockpit/gravitee-cockpit/gravitee-cockpit-ui/node_modules/terser/dist/bundle.min.js:3427:20)
    at expression (/Users/jgiovaresco/DEV/gravitee/cockpit/gravitee-cockpit/gravitee-cockpit-ui/node_modules/terser/dist/bundle.min.js:3452:24)


```
